[package]
authors = ["Mikhail Kviatkovskii <mikhail.kviatkovskii@pm.me>"]
description = "Rust implementation of Indigo cheminformatics toolkit"
edition = "2021"
homepage = "https://github.com/mkviatkovskii/indigo-rust"
keywords = ["cheminformatics", "smiles", "fingerprint", "indigo", "rust"]
license = "Apache-2.0"
name = "indigo-rust"
readme = "README.md"
repository = "https://github.com/mkviatkovskii/indigo-rust.git"
version = "0.0.1"

[dependencies]
bit-set = "0.5.3"
bit-vec = "0.6.3"
nom = "7.1.3"
petgraph = "0.6.3"
